name: neemba
networks:
  appnet:
    driver: bridge

volumes:
  nats-data:

services:
  reverse-proxy:
    image: caddy:2.8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./infra/certs:/data
    depends_on:
      - node
      - python
    networks:
      - appnet
    restart: unless-stopped

  node:
    build:
      context: ./services/node
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    expose:
      - "3000"
    networks:
      - appnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5

  python:
    build:
      context: ./services/python
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env.prod
    expose:
      - "8000"
    networks:
      - appnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5

  nats:
    image: nats:2.10.17-alpine
    command: ["-c", "/etc/nats/nats.conf"]
    env_file:
      - .env.prod
    expose:
      - "4222"
      - "8222"
    volumes:
      - nats-data:/data
      - /srv/neemba/infra/nats/nats.conf:/etc/nats/nats.conf:ro
    networks:
      - appnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8222/varz"]
      interval: 10s
      timeout: 3s
      retries: 6
