global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["node:3000"]

  - job_name: "python"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["python:8000"]

  - job_name: "nginx"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["nginx-exporter:9113"]
